####
GET http://localhost:3000/banksva HTTP/1.1
content-type: application/json

####
POST http://localhost:3000/subscription HTTP/1.1
Content-Type: application/x-www-form-urlencoded

// EXTERNAL ID =  ID USER DARI SUPER WHATSAPP
external_id=ABC_099915 
&name=Yan sb
&email=yan.septyadi@gmail.com
&amount=65000
&description= Invoice for SuperWA Subscription
&currency= IDR

####
GET http://localhost:3000/checksubs?id=615abd3a9b2db7b5d35ba3ab HTTP/1.1
Content-Type: application/json

####
POST http://localhost:3000/stopsubs HTTP/1.1
Content-Type: application/x-www-form-urlencoded

// ID RECCURING DARI XENDIT
id=615abd3a9b2db7b5d35ba3ab

####
POST http://localhost:3000/changesubs HTTP/1.1
Content-Type: application/x-www-form-urlencoded

// ID RECCURING DARI XENDIT
id=615abd3a9b2db7b5d35ba3ab
&amount=85000